# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html', stylish, json, tap, unix, visualstudio junit - https://github.com/eslint/eslint/tree/master/lib/formatters
  formatter: stylish
  # Output file instead of logging results
  # output-file: 'reports/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 10
# File Options
files:
  include: 'src/scss/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
   # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 1
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-protocols: 0
  no-vendor-prefixes: 2
  no-warn: 1
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 1
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format: 0
  function-name-format: 2
  id-name-format: 0
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2

  # Style Guide
  attribute-quotes: 2
  bem-depth: 0
  border-zero:
    - 2
    -
      convention: none
  brace-style:
    - 2
    - style: stroustrup
    - allow-single-line: false
  clean-import-paths: 2
  empty-args: 2
  hex-length:
    - 1
    -
      style: shor
  hex-notation:
    - 2
    -
      style: lowercase
  indentation: 2
  leading-zero:
    - 0
    - include: false
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
    - 2
    - max-depth: 6
  property-sort-order: 2
  pseudo-element: 1
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2


  # extends-before-mixins: 2
  # extends-before-declarations: 2
  # placeholder-in-extend: 2
  # mixins-before-declarations:
  #   - 2
  #   -
  #     exclude:
  #       - breakpoint
  #       - mq

  # no-warn: 1
  # no-debug: 1
  # no-ids: 2
  # no-important: 1
  # hex-notation:
  #   - 2
  #   -
  #     style: lowercase
  # indentation:
  #   - 2
  #   -
  #     size: 2
  # property-sort-order:
  #   - 1
  #   - ignore-custom-properties: true
  # variable-for-property:
  #   - 0
  #   -
  #     properties:
  #       - margin
  #       - content
  # border-zero:
  #   - 2
  #   -
  #     convention: none
  # pseudo-element: 1

  # nesting-depth:
  #   - 2
  #   - max-depth: 3

  # url-quotes: 2


  # http://sasstools.github.io/make-sass-lint-config/
  # bem-depth:
  #   - 0
  #   - max-depth: 1
  # border-zero:
  #   - 2
  #   -
  #     convention: none
  # brace-style:
  #   - 1
  #   - allow-single-line: true
  # class-name-format:
  #   - 1
  #   - convention: hyphenatedlowercase
  # clean-import-paths:
  #   - 1
  #   - filename-extension: false
  #     leading-underscore: false
  # empty-line-between-blocks:
  #   - 1
  #   - ignore-single-line-rulesets: true
  # extends-before-declarations: 1
  # extends-before-mixins: 1
  # final-newline:
  #   - 1
  #   - include: true
  # force-attribute-nesting: 1
  # force-element-nesting: 1
  # force-pseudo-nesting: 1
  # function-name-format:
  #   - 1
  #   - allow-leading-underscore: true
  #     convention: hyphenatedlowercase
  # hex-length:
  #   - 1
  #   - style: short
  # hex-notation:
  #   - 1
  #   - style: lowercase
  # id-name-format:
  #   - 1
  #   - convention: hyphenatedlowercase
  # indentation:
  #   - 1
  #   - size: 2
  # leading-zero:
  #   - 1
  #   - include: false
  # mixin-name-format:
  #   - 1
  #   - allow-leading-underscore: true
  #     convention: hyphenatedlowercase
  # mixins-before-declarations: 1
  # nesting-depth:
  #   - 1
  #   - max-depth: 3
  # no-color-keywords: 1
  # no-color-literals: 1
  # no-css-comments: 1
  # no-debug: 1
  # no-duplicate-properties: 1
  # no-empty-rulesets: 1
  # no-extends: 0
  # no-ids: 1
  # no-important: 1
  # no-invalid-hex: 1
  # no-mergeable-selectors: 1
  # no-misspelled-properties:
  #   - 1
  #   - extra-properties: []
  # no-qualifying-elements:
  #   - 1
  #   - allow-element-with-attribute: false
  #     allow-element-with-class: false
  #     allow-element-with-id: false
  # no-trailing-zero: 1
  # no-transition-all: 0
  # no-url-protocols: 1
  # no-vendor-prefixes:
  #   - 1
  #   - additional-identifiers: []
  #     excluded-identifiers: []
  # placeholder-in-extend: 1
  # placeholder-name-format:
  #   - 1
  #   - convention: hyphenatedlowercase
  # property-sort-order:
  #   - 1
  #   - ignore-custom-properties: false
  # property-units:
  #   - 1
  #   - global:
  #       - ch
  #       - em
  #       - ex
  #       - rem
  #       - cm
  #       - in
  #       - mm
  #       - pc
  #       - pt
  #       - px
  #       - q
  #       - vh
  #       - vw
  #       - vmin
  #       - vmax
  #       - deg
  #       - grad
  #       - rad
  #       - turn
  #       - ms
  #       - s
  #       - Hz
  #       - kHz
  #       - dpi
  #       - dpcm
  #       - dppx
  #       - '%'
  #     per-property: {}
  # quotes:
  #   - 1
  #   - style: single
  # shorthand-values:
  #   - 1
  #   - allowed-shorthands:
  #       - 1
  #       - 2
  #       - 3
  # single-line-per-selector: 1
  # space-after-bang:
  #   - 1
  #   - include: false
  # space-after-colon:
  #   - 1
  #   - include: true
  # space-after-comma:
  #   - 1
  #   - include: true
  # space-before-bang:
  #   - 1
  #   - include: true
  # space-before-brace:
  #   - 1
  #   - include: true
  # space-before-colon: 1
  # space-between-parens:
  #   - 1
  #   - include: false
  # trailing-semicolon: 1
  # url-quotes: 1
  # variable-for-property:
  #   - 0
  #   - properties: []
  # variable-name-format:
  #   - 1
  #   - allow-leading-underscore: true
  #     convention: hyphenatedlowercase
  # zero-unit: 1
